name = "tash"
description = "Binding to Tcl/Tk"
long-description = """
Tash (previously known as Tcl Ada Shell) 
is an Ada binding to Tcl/Tk.

Its purpose is to

* allow a Tcl program to use Ada in place of C to implement Tcl
  commands where additional execution speed, more complex data
  structures, or better name space management is needed, and

* support the rapid development of Platform-Independent Graphical User
  Interfaces via Tk.
"""
website = "https://github.com/simonjwright/tcladashell"
version = "8.7.0-dev"
licenses = "GPL-2.0-or-later WITH GCC-exception-2.0"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

project-files = ["tash.gpr"]

tags = ["scripting", "tcl", "tk"]

[[depends-on]]
  "libtcl" = "*"
  "libtk" = "*"

[gpr-set-externals.'case(os)']
windows = { TCLADASHELL_PLATFORM = "windows" }
linux = { TCLADASHELL_PLATFORM = "linux" }
macos = { TCLADASHELL_PLATFORM = "macos" }

[[actions]]
type = "post-fetch"
command = ["make", "-C", "src", "tcl_record_sizes.ads"]
