name = "tcladashell"
description = "Binding to Tcl/Tk"
website = "https://github.com/simonjwright/tcladashell"
version = "8.7.0-dev"
licenses = "GPL-2.0-or-later WITH GCC-exception-2.0"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

project-files = ["tash.gpr"]

tags = ["scripting", "tcl", "tk"]

[[depends-on]]
  "libtcl" = "*"
  "libtk" = "*"

[gpr-set-externals.'case(os)']
windows = { TCLADASHELL_PLATFORM = "windows" }
linux = { TCLADASHELL_PLATFORM = "linux" }
macos = { TCLADASHELL_PLATFORM = "macos" }

