--  Configuration for tash_tests generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Tash_Tests_Config is
   pragma Pure;

   Crate_Version : constant String := "8.0.0";
   Crate_Name : constant String := "tash_tests";

   Alire_Host_OS : constant String := "macos";

   Alire_Host_Arch : constant String := "aarch64";

   Alire_Host_Distro : constant String := "distro_unknown";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := release;

end Tash_Tests_Config;
