/* Configuration for tcladashell generated by Alire */
#ifndef TCLADASHELL_CONFIG_H
#define TCLADASHELL_CONFIG_H

#define CRATE_VERSION "8.7.0-dev"
#define CRATE_NAME "tcladashell"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "distro_unknown"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
