---

name: CI Linux

on:
  push:
  pull_request:

jobs:
  build:
    name: CI on linux

    runs-on: linux-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: alire-project/setup-alire
      uses: alire-project/setup-alire@v1
    -
      name: Add local index
      run: |
        alr --non-interactive index --add=git+https://github.com/simonjwright/local-alire-index --name=local
    -
      name: Install toolchain
      run: |
        alr --non-interactive config --global --set toolchain.assistant false
        alr --non-interactive toolchain --install gnat_native
        alr --non-interactive toolchain --install gprbuild
        alr --non-interactive toolchain --select gnat_native
        alr --non-interactive toolchain --select gprbuild
    -
      name: Build and run
      run: |
        # flags for tk include those for tcl
        export CFLAGS=$(pkg-config --cflags tk8.6)
        export LDFLAGS=$(pkg-config --libs tk8.6)
        cd tests; alr --non-interactive build; ./tashtest tashtest.tcl
